version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: user-engine-mongodb
    restart: always
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./.docker/mongodb/db:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
