apiVersion: skaffold/v1
kind: Config
metadata:
  name: dev-k8s-user-engine
build:
  # local:
  #   push: false
  artifacts:
    - image: newerton/user-engine
      context: .
      docker:
        dockerfile: Dockerfile.prod
      sync:
        manual:
          - src: 'src/**/*.*'
            dest: .
deploy:
  # kubeContext: docker-desktop
  kubectl:
    flags:
      global: [--namespace=nestjs-k8s-namespace]
    manifests:
      - ./k8s/01-secrets.yaml
      - ./k8s/02-app.yaml
