apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-k8s-namespace
  name: user-engine
spec:
  type: LoadBalancer
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: user-engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nestjs-k8s-namespace
  name: user-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-engine
  template:
    metadata:
      labels:
        app: user-engine
    spec:
      # imagePullSecrets:
      #   - name: registry-secret
      containers:
        - name: user-engine
          image: newerton/user-engine:latest
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: user-engine-k8s-secret
